/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package practica1_listas.vista;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.xml.bind.JAXBException;
import practica1_listas.Utilidades.Utilidades;
import practica1_listas.controlador.EmpresaController;
import practica1_listas.modelo.Trabajador;
import practica1_listas.vista.modeloTabla.ModeloTablaTrabajadores;

/**
 *
 * @author leomah
 */
public class Principal extends javax.swing.JDialog {

    private EmpresaController ec = new EmpresaController();
    private ModeloTablaTrabajadores mt = new ModeloTablaTrabajadores();

    /**
     * Creates new form Principal
     */
    public Principal(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public void cargarTabla() {
        if (ec.getEmpresa().getTrabajadorList() != null) {
            mt.setTrabajadores(ec.getEmpresa().getTrabajadorList());
            jTable1.setModel(mt);
            jTable1.updateUI();
        } else {
            JOptionPane.showMessageDialog(null, "Agrege empleados");
        }

    }

    public void limpiar() {
        txtNombresTrabajador.setText("");
        txtApellidos.setText("");
        txtAnio.setText("");
        txtMes.setText("");
        txtDia.setText("");
        txtSueldo.setText("");
    }

    public void guardarEmpresa() {
        if (!txtNombreEmpresa.getText().isEmpty()) {
            ec = new EmpresaController(txtNombreEmpresa.getText());
            cargarTabla();
            JOptionPane.showMessageDialog(null, "Se ha guardado");
        } else {
            JOptionPane.showMessageDialog(null, "Ingrese el nombre de la empresa");
        }
    }

    public void guardarEmpleado() {
        if (txtNombresTrabajador.getText().isEmpty() || txtApellidos.getText().isEmpty()
                || txtSueldo.getText().isEmpty() || txtAnio.getText().isEmpty()
                || txtDia.getText().isEmpty() || txtMes.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese los datos completos");
        } else {
            Calendar c1 = Calendar.getInstance();
            c1.set(Integer.parseInt(txtAnio.getText()), Integer.parseInt(txtMes.getText()), Integer.parseInt(txtDia.getText()));
            Trabajador t1 = new Trabajador(txtNombresTrabajador.getText(), txtApellidos.getText(), Float.parseFloat(txtSueldo.getText()), c1);
            t1.setAniosEmpleo(Utilidades.calcularAniosEmpleo(c1));
            t1.setRango(Utilidades.obtenerRango(t1));
            t1.setBono(Utilidades.obtenerBono(t1.getRango()));
            t1.setSueldoFinal(Utilidades.obtenerSueldoFinal(t1));
            t1.setPagado(false);
            ec.guardarTrabajador(t1);
            limpiar();
            cargarTabla();
            JOptionPane.showMessageDialog(null, "Se ha guardado");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombresTrabajador = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtSueldo = new javax.swing.JTextField();
        txtAnio = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtMes = new javax.swing.JTextField();
        txtDia = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnGuardarEmpresa = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtNombreEmpresa = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btnGuardarJSON = new javax.swing.JMenuItem();
        btnCargarJson = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 830, 250));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Trabajador"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombres:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel2.setText("Apellidos:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel3.setText("Sueldo:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel4.setText("Fecha Ingreso:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));
        jPanel2.add(txtNombresTrabajador, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 310, -1));
        jPanel2.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 310, -1));
        jPanel2.add(txtSueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 310, -1));
        jPanel2.add(txtAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 70, -1));

        jLabel7.setText("Año:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, -1, -1));

        jLabel8.setText("Mes:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, -1, -1));
        jPanel2.add(txtMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 40, -1));
        jPanel2.add(txtDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 40, -1));

        jLabel9.setText("Dia:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, -1, -1));

        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel2.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 830, 190));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Empresa"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Cantarell", 3, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("NOMBRE EMPRESA");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        btnGuardarEmpresa.setText("GUARDAR");
        btnGuardarEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarEmpresaActionPerformed(evt);
            }
        });
        jPanel3.add(btnGuardarEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, -1, -1));

        jLabel10.setText("Nombre:");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        txtNombreEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreEmpresaActionPerformed(evt);
            }
        });
        jPanel3.add(txtNombreEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 310, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 830, 120));

        jMenu1.setText("Archivo");

        btnGuardarJSON.setText("Guardar");
        btnGuardarJSON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarJSONActionPerformed(evt);
            }
        });
        jMenu1.add(btnGuardarJSON);

        btnCargarJson.setText("Cargar");
        btnCargarJson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarJsonActionPerformed(evt);
            }
        });
        jMenu1.add(btnCargarJson);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 895, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreEmpresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreEmpresaActionPerformed

    private void btnGuardarEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarEmpresaActionPerformed
        guardarEmpresa();
    }//GEN-LAST:event_btnGuardarEmpresaActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        guardarEmpleado();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnGuardarJSONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarJSONActionPerformed
        try {
            Utilidades.guardarJSON(ec);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGuardarJSONActionPerformed

    private void btnCargarJsonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarJsonActionPerformed
        try {
            // TODO add your handling code here:
            this.ec = Utilidades.leerJson();
            cargarTabla();
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCargarJsonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Principal dialog = new Principal(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnCargarJson;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnGuardarEmpresa;
    private javax.swing.JMenuItem btnGuardarJSON;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtDia;
    private javax.swing.JTextField txtMes;
    private javax.swing.JTextField txtNombreEmpresa;
    private javax.swing.JTextField txtNombresTrabajador;
    private javax.swing.JTextField txtSueldo;
    // End of variables declaration//GEN-END:variables
}
